config.load_autoconfig()


c.url.default_page = "about:blank"
c.url.start_pages = 'about:blank'

# Gruvbox Dark theme
c.colors.completion.fg = '#ebdbb2'
c.colors.completion.odd.bg = '#282828'
c.colors.completion.even.bg = '#282828'
c.colors.completion.category.fg = '#fabd2f'
c.colors.completion.category.bg = '#282828'
c.colors.completion.category.border.top = '#282828'
c.colors.completion.category.border.bottom = '#282828'
c.colors.completion.item.selected.fg = '#282828'
c.colors.completion.item.selected.bg = '#689d6a'
c.colors.completion.item.selected.border.top = '#689d6a'
c.colors.completion.item.selected.border.bottom = '#689d6a'
c.colors.completion.match.fg = '#d65d0e'
c.colors.statusbar.normal.fg = '#ebdbb2'
c.colors.statusbar.normal.bg = '#282828'
c.colors.statusbar.insert.fg = '#282828'
c.colors.statusbar.insert.bg = '#83a598'
c.colors.statusbar.passthrough.fg = '#282828'
c.colors.statusbar.passthrough.bg = '#d3869b'
c.colors.statusbar.command.fg = '#ebdbb2'
c.colors.statusbar.command.bg = '#282828'
c.colors.statusbar.url.fg = '#ebdbb2'
c.colors.statusbar.url.success.http.fg = '#98971a'
c.colors.statusbar.url.success.https.fg = '#689d6a'
c.colors.statusbar.url.error.fg = '#fb4934'
c.colors.statusbar.url.warn.fg = '#d79921'
c.colors.statusbar.url.hover.fg = '#83a598'
c.colors.tabs.bar.bg = '#282828'
c.colors.tabs.odd.fg = '#ebdbb2'
c.colors.tabs.odd.bg = '#282828'
c.colors.tabs.even.fg = '#ebdbb2'
c.colors.tabs.even.bg = '#282828'
c.colors.tabs.selected.odd.fg = '#282828'
c.colors.tabs.selected.odd.bg = '#689d6a'
c.colors.tabs.selected.even.fg = '#282828'
c.colors.tabs.selected.even.bg = '#689d6a'
c.colors.hints.fg = '#282828'
c.colors.hints.bg = '#fabd2f'
c.colors.hints.match.fg = '#ebdbb2'
c.colors.downloads.bar.bg = '#282828'
c.colors.downloads.start.fg = '#282828'
c.colors.downloads.start.bg = '#458588'
c.colors.downloads.stop.fg = '#282828'
c.colors.downloads.stop.bg = '#689d6a'
c.colors.webpage.darkmode.enabled = True

# Font
c.fonts.default_family = 'JetBrainsMono Nerd Font'
c.fonts.default_family = 'JetBrainsMono NF'
c.fonts.default_family = 'JetBrains Mono NL Nerd Font'

c.fonts.default_size = '11pt'
